const enum Skill {
  Apollo = "Apollo",
  AWS = "AWS",
  Bootstrap = "Bootstrap",
  ChromeX = "Chrome Extensions",
  Cplusplus = "C++",
  Emotion = "Emotion",
  Flowbite = "Flowbite",
  Jest = "Jest",
  GraphQL = "GraphQL",
  Hack = "Hack",
  Mantine = "Mantine",
  MaterialUI = "Material UI",
  Mathematica = "Wolfram Mathematica",
  MATLAB = "MATLAB",
  MySQL = "MySQL",
  NestJS = "NestJS",
  NextJS = "Next.js",
  Node = "Node.js",
  PostgreSQL = "PostgreSQL",
  Puppeteer = "Puppeteer",
  Python = "Python",
  React = "React",
  Relay = "Relay",
  Remix = "Remix",
  SCSS = "SCSS",
  SFML = "SFML",
  SST = "SST",
  TailwindCSS = "TailwindCSS",
  Thrift = "Thrift",
  TypeScript = "TypeScript",
  VanillaExtract = "Vanilla Extract",
  Vercel = "Vercel",
}

export default Skill;
